Repository V-core9/V-Web-Gears, pull requests merged in 2021-11, with the labels that each got.

#1 Create codeql-analysis.yml
  .github/workflows/codeql-analysis.yml
Labels: duplicate, enhancement

#17 Create label.yml
  .github/workflows/label.yml
Labels: documentation, enhancement, good first issue, invalid

#19 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation, duplicate, enhancement, good first issue

#20 just the deepsource toml file
  .deepsource.toml
Labels: duplicate, enhancement

#21 Update README.md
  README.md
Labels: documentation, duplicate, good first issue

#22 Add a Codacy badge to README.md
  README.md
Labels: documentation, duplicate, enhancement

#23 sorted out so it only has md files and not a bunch of crap for no good reason
  _system/badges/codacy.com__code-quality.md
  _system/badges/deepsource.io__active.issues.md
  _system/badges/deepsource.io__resolved.issues.md
  _system/badges/github.com__CodeQL.md
Labels: bug, documentation, duplicate, enhancement

#25 Badges Fix for file naming
  _system/badges/[codacy.com]code-quality.md
  _system/badges/deepsource.io,resolved.issues.md
  _system/badges/deepsource.io-.-active.issues.md
  _system/badges/github.com_CodeQL.md
Labels: 👻 bug, 🚀 good first issue

#27 Title change in characters around the icon badge
  README.md
Labels: 👻 bug, 📑 documentation, 🦆 duplicate, 📡 enhancement

#28 Create njsscan-analysis.yml
  .github/workflows/njsscan-analysis.yml
Labels: 🦆 duplicate, 📡 enhancement, 🚀 good first issue

#29 small fix
  _system/badges/codacy.code-quality.md
  _system/badges/deepsource.active-issues.md
  _system/badges/deepsource.resolved-issues.md
  _system/badges/github.com-CodeQL.md
Labels: 🦆 duplicate, 📡 enhancement, 🤦‍♂️ help wanted, 🚀 good first issue

#30 yea init for it
  bg_run/index.js
Labels: 👻 bug, 🦆 duplicate, 📡 enhancement

#31 yea more fuking link
  _system/badges/codacy.code-quality.md
  _system/badges/deepsource.active-issues.md
  _system/badges/deepsource.resolved-issues.md
  _system/badges/github.com-CodeQL.md
  cli/README.md
  cli/package.json
  package.json
Labels: 📑 documentation, 📡 enhancement
